# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'XFWeiboSwift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'SnapKit', '~> 0.21.1'
pod 'HYLabel'
pod 'BHBPopView'


  # Pods for XFWeiboSwift

  target 'XFWeiboSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XFWeiboSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
